### ISSUE TITLE
[RM] *. tab no funciona

### ISSUE THREAD

**Issue by CeciliaRodriguez** [CeciliaRodriguez/mariobash#12]

**Comment by mgarciaisaia** [comment]
Ojo, `*` nunca permite hacer autocomplete, justamente porque matchea con cualquier cosa. En una terminal posta, `rm *<tab>` no autocompleta nada.

**Comment by CeciliaRodriguez** [comment]
mala mía :blush:, en algún punto testeando por 1000 vez esperé que cuando hacía rm *.tab me autocompletara los hongos marrones  ja
