### ISSUE TITLE
El comando "Exit" rompe la pestana

### ISSUE THREAD

**Issue by afilgueira** [CeciliaRodriguez/mariobash#27]
Rarisimo :/

**Comment by CeciliaRodriguez** [comment]
es una boludes, quedó puesto como comando disponible en cualquier directorio y como no esta implementado rompe

**Comment by afilgueira** [comment]
Genia!!!

2017-04-12 11:02 GMT-03:00 CeciliaRodriguez <notifications@github.com>:
